artifacts_dir: artifacts
audio_file: artifacts/output.mp3
video_file: artifacts/final_video.mp4
client_secret_file: client_secret.json
bucket_name: ai-audio-bucket

database:
  host: localhost
  port: 5432
  user: postgres
  password: 0jpugnwz0
  dbname: youtube_pipeline

smtp_server:
  host: smtp.gmail.com
  port: 587
  sender: ckryusuff3@gmail.com
  password: bynmrgbzrzkvsivy # app password get from google
